server:
  port: 4582

spring:
  application:
    name: query_service

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: eidiko
    password: sarasu10
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true