server:
  port: 4582

spring:
  application:
    name: query_service

  datasource:
    username: ${ORACLE_DB_USER}
    password: ${ORACLE_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${ORACLE_DB_URL}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true