server:
  port: 4580

spring:

  datasource:
    username: ${ORACLE_DB_USER}
    password: ${ORACLE_DB_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${ORACLE_DB_URL}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#logging:
#  file:
#    name: logs/app.log

  level:
    org:
      springframework.security: DEBUG