server:
  port: 4581
spring:
  application:
    name: KekeActionService
  datasource:
    username: keka
    password: sarasu10
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1522:xe

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
