server:
  port: 4581

spring:
  application:
    name: KekeActionService
  datasource:
    username: keka_clone
    password: sarasu10
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.3.30:1521:xe
  mail:
    username: abhishekghogare.eidiko@gmail.com
    password: ${APP_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
