server:
  port: 4581

spring:
  application:
    name: KekeActionService
  datasource:
    username: ${ORACLE_DB_USER}
    password: ${ORACLE_DB_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe


  jpa:
    hibernate:
      ddl-auto: none #update
    show-sql: true

  mail:
    username: ${EMAIL}
    password: ${APP_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

